USE [master]
GO

/****** Object:  Database [EdDb]    Script Date: 9/16/2021 9:51:37 AM ******/
CREATE DATABASE [EdDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EdDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EdDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EdDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EdDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EdDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EdDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EdDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EdDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EdDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EdDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [EdDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [EdDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EdDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EdDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EdDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EdDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EdDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EdDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EdDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EdDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EdDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EdDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EdDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EdDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EdDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EdDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EdDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EdDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EdDb] SET  MULTI_USER 
GO

ALTER DATABASE [EdDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EdDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EdDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EdDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EdDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EdDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EdDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EdDb] SET  READ_WRITE 
GO

